[package]
name = "udpate_generator"
version = "0.4.0"
authors = ["potolicynam <potolicynam@tehnologia.com>"]
build = "build.rs"

[dependencies]

config = "*"
log = "*"
simplelog = "*"

# time-work
chrono = "*"

fs_extra = "*"
regex = "*"
encoding_rs = "*"

# gui
sciter-rs = "*"
